import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from "./component/hero";
import Product from './component/product';

export default function Home() {
  return (
    // <div className={styles.container}>
    <div>

      <Head>
        <title>สวนส้มจินตนา</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Kanit" rel="stylesheet" />
        <link rel="stylesheet" href="bower_components/aos/dist/aos.css" />
        <link href="./vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="./vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" />
        <link href="./vendor/boxicons/css/boxicons.min.css" rel="stylesheet" />
        <link href="./vendor/glightbox/css/glightbox.min.css" rel="stylesheet" />
        <link href="./vendor/swiper/swiper-bundle.min.css" rel="stylesheet" />
        <link href="https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.css" rel="stylesheet" />

        <script dangerouslySetInnerHTML={{
          __html: `AOS.init({
            duration: 1000,
            easing: 'ease-in-out',
            once: true,
            mirror: false
          })`
        }} />

        <script src="bower_components/aos/dist/aos.js"></script>
        <script src="./vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="./vendor/glightbox/js/glightbox.min.js"></script>
        <script src="./vendor/isotope-layout/isotope.pkgd.min.js"></script>
        <script src="./vendor/php-email-form/validate.js"></script>
        <script src="./vendor/purecounter/purecounter.js"></script>
        <script src="./vendor/swiper/swiper-bundle.min.js"></script>
        <script src="./js/main.js"></script>
        {/* <script async defer
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAjI-xgJuRrbdGY328DYy6u3qu16BfZa-U&callback=initMap"
          type="text/javascript"></script> */}
        <script dangerouslySetInnerHTML={{
          __html: `(function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
          }, i[r].l = 1 * new Date(); a = s.createElement(o),
          m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
      })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

      ga('create', 'UA-XXXXX-Y', 'auto');
      ga('send', 'pageview');`}} />

      </Head>
      <main>
        <Hero />
        <Product />
      </main>

      {/* <main className={styles.main}> */}
      {/* </main> */}

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}

    </div>
  )
}
